### ISSUE TITLE
Does `required` and `optional` apply to categorical output types

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/schemas#10]
Given probabilities across all possible categories sum to 1, it doesn't make much sense to me to have some categories optional and some required? 

If anything feels like they should either all be required or all optional (with any missing assumed to be 0 probability) so long as what is provided sums to one?

**Comment by nickreich** [comment]
I like a plan where all categories are optional (with any missing assumed to be 0 probability) with a check that the probabilities provided sum to one.

Some example categories:
Example 1, like a level of incidence : ["low", "moderate", "high", "extreme"]
Example 2, like a trend: ["flat", "increasing", "decreasing"]

**Comment by elray1** [comment]
I have a vague memory that maybe the US SMH was allowing teams to submit forecasts for different sets of age group categories? Maybe @LucieContamin has input here?

**Comment by annakrystalli** [comment]
Closed via #11
