### ISSUE TITLE
"submissions_due.relative_to" property should be optional

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/schemas#3]
The `relative_to` property of `submissions_due` is listed as required [here](https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/0683d88c79b50626cc1b1e0beed3c8a04372d8b6/tasks-schema.json#L411), but I think it should be optional -- a hub may want to specify an exact range of submission due dates as in the example scenario hub [here](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub/blob/9971e9c177522944d82d2864217669be983b6364/hub-metadata/tasks.json#L32-L35).

**Comment by annakrystalli** [comment]
The `submission_due` has two options for how it can be defined indicated by the `oneOf` keyword.  `relative_to` is only required when `submission_due` matches the first pattern. At the bottom of the `submission_due` property specification it states that only  `"start"` and "`end"` are required (but that might actually be unnecessary come to think of it!

```json
          "submissions_due": {
            "type": "object",
            "oneOf": [{
                "properties": {
                  "relative_to": {
                    "type": "string"
                  },
                  "start": {
                    "type": "integer"
                  },
                  "end": {
                    "type": "integer"
                  }
                },
                "required": [
                  "relative_to",
                  "start",
                  "end"
                ]
              },
              {
                "properties": {
                  "start": {
                    "type": "string",
                    "format": "date"
                  },
                  "end": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "start",
                  "end"
                ]
              }
            ],
            "required": [
              "start",
              "end"
            ]
          },
```

**Comment by elray1** [comment]
Got it, thanks for the clarification!
