### ISSUE TITLE
nomenclature about `type`, `output_type`, and `target_type`

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/schemas#49]
Currently in the hub `tasks.json`, we have:

1. `model_tasks` > `output_type`, which describes a representation or summary of a probability distribution and lines up with the `type` column in a model output submission file
2. `model_tasks` > `target_metadata` > `target_type`, which describes a statistical variable type

Maybe we should have a more consistent naming for the two things in point 1?  e.g., might we want to change the column name in submission files to `output_type` rather than just `type`?

**Comment by annakrystalli** [comment]
Happy with this and makes sense to me.

Let me know whether to go ahead and implement .

Main changes required will be to:
- hubDocs: documentation on `model-output` data format
- Example hubs (both test mini-hubs in `inst` and any full example hubs)

**Comment by annakrystalli** [comment]
This is complete in `hubUtils`. Still needs addressing in `hubDocs` but issue exists: https://github.com/Infectious-Disease-Modeling-Hubs/hubDocs/issues/50.

Closing here
