### ISSUE TITLE
Add round name information

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/schemas#5]
Per suggestion from @shauntruelove , the `tasks.json` file has a `round_id` field that can be a string. 
In the [scenario complex example repo](https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub), the `tasks.json` has multiple date as `round_id`. 
The dates are used to identify each round in the filename, content of the files, etc. However, we also identify the name by round, for example, round 1 is the date "2020-01-01". 

Should we either add a round_name field in the `tasks.json` file or should we have a specific place in the repo to store that information in a different format? or both?

**Comment by annakrystalli** [comment]
I'm in favour of this idea and will add it to the current draft. We can finalise the decision at the PR review stage 👍

**Comment by annakrystalli** [comment]
Closed via #11
