### ISSUE TITLE
Add `forecast_date` / `target_end_date` properties to schema?

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/schemas#53]
In our schema we currently have a `origin_date`:

https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/c1d8fc0e993ed07c2d783becbe91ea10e31c7e85/v1.0.0/tasks-schema.json#L51C42-L60

and a `target_date` property:

https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/c1d8fc0e993ed07c2d783becbe91ea10e31c7e85/v1.0.0/tasks-schema.json#L268-L306

Have we settled on whether `forecast_date` (or other) / `target_end_date` represent standard concepts and should therefore have schema properties for validating them when included in `tasks.json` files?

**Comment by annakrystalli** [comment]
cc @nickreich @rborchering

**Comment by nickreich** [comment]
My sense is that we should add some of these "standard" fields to the schema.

- `forecast_date` and `reference_date` could be synonymous with `origin_date`. Given that different groups seem to have different preferences or reasons for liking different versions of these, maybe we just list them all and largely be agnostic about which one a hub picks?
- `target_end_date` I do think could be valuable to include also, as a standard way of referring to the final date of the time unit being predicted for.
