### ISSUE TITLE
rename `type_id` to `output_type_id`

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/schemas#55]
e.g. see [this line](https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/c1d8fc0e993ed07c2d783becbe91ea10e31c7e85/v1.0.0/tasks-schema.json#L403)

[Elsewhere](https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/71), we have decided to name this `output_type_id` rather than `type_id`, but it seems like the schemas here have not been updated yet. Is this intentional, or just an oversight?

**Comment by annakrystalli** [comment]
I don't remember discussion of the schema changing too. 

My understanding was that it was the way the schema was already laid out (with `type_id` and `type` as sub-properties of `output_type`) that was causing folks to want columns in model_output data to be `output_type` and `output_type_id`.

**Comment by elray1** [comment]
The way I have thought about this, this configuration setting in a hub's tasks.json file is specifying details about the values in the `output_type_id` column of model output files, so it would be cleanest/clearest if the json field name was also `output_type_id`, to establish a clear connection between the names of things in the config file and the name of the column in the model outputs that it is describing.

**Comment by annakrystalli** [comment]
Sounds fair indeed. It will mean breaking changes in all current example/test hubs and `hubUtils` functionality though. 
I'm actually considering making `hubUtils` functionality back compatible with the current version of the schema, at least for a while?
